### ISSUE TITLE
Add config options for schema

### ISSUE THREAD

**Issue by jbrunton** [jbrunton/gflows#13]
Something like:
```
checks:
  schema:
    enabled: true
    source: ...
overrides:
  my-workflow:
    checks:
      schema: false
```
