### ISSUE TITLE
Question (ytt) - how to add several steps

### ISSUE THREAD

**Issue by kbakk** [jbrunton/gflows#198]
Hi,

I'm trying to add several steps, e.g

```yaml
- uses: actions/cache@v2
  id: cache
  with:
    path: |
      **/node_modules
    key: cache-${{ runner.os }}-${{ hashFiles('**/package.json', 'yarn.lock') }}
- name: Install packages
  run: yarn install
```

I've experimented a bit, and found that I can use:

```yaml
#@ for/end val in test():
-  #@ val
```

But I can't get this work, if `test()` is defined as:

```
#@ def test():
- name: test 9
  run: echo 9

- name: test 1
  run: echo 1

- name: test 2
  run: echo 2
#@ end

```

I then get an error:

```
      error .github/workflows/build.yml (from .gflows/workflows/build)
  ► - cannot load steps.lib.yml: Unmarshaling YAML template 'steps.lib.yml': yaml: line 8: did not find expected <document start>
      error .github/workflows/gflows.yml (from .gflows/workflows/gflows)
  ► - cannot load steps.lib.yml: Unmarshaling YAML template 'steps.lib.yml': yaml: line 8: did not find expected <document start>
```

This works on the [playground](https://carvel.dev/ytt/#playground):

![image](https://user-images.githubusercontent.com/24817039/115057167-00516b00-9ee4-11eb-87cb-ddf6f61aa7e4.png)

I did find that I could define `test()` as several documents. It works, but it looks a bit strange:

![image](https://user-images.githubusercontent.com/24817039/115056426-21fe2280-9ee3-11eb-9023-e51714e39ea3.png)

Is this a limitation in ytt, or in gflows?

Anyways, thanks for creating this library! 🙌

**Comment by jbrunton** [comment]
Hi @kbakk: I'm not a ytt expert, but I believe this error occurs because, in the words of dkalinin in [this thread](https://kubernetes.slack.com/archives/CH8KCCKA5/p1602518344380300) on the Kubernetes Slack:

> ytt templates are expected to be valid yaml. because of that its not enough to rely on function "boundaries" (def and end lines) to separate different types of content (in your case an array used inside the function and the rest of the document).
>
> https://get-ytt.io/#example:example-function uses yaml doc separator on lines 31 and 46 to make sure array (line 43) is separated from map (line 47).

I see that your screenshot from your first example in the playground does include a document separator (`---`). Can you confirm whether your source files for the workflow includes an appropriate document separator too? (EDIT: This is why splitting across several files also works, but it should be possible to combine multiple yaml documents into a single file using separators.)

**Comment by kbakk** [comment]
Thanks for the links, that did help solve this issue.

So defining 

```yaml
#@ def test():
- name: test 9
  run: echo 9

- name: test 1
  run: echo 1

- name: test 2
  run: echo 2
#@ end
```

in a separate file does work (sorry, I didn't include that in the description because I didn't consider it would make a difference). 

What I was trying was this:

```yaml
#@ def setup_go():
  uses: actions/setup-go@v2
  with:
    go-version: "^1.14.4"
#@ end

#@ def test_a():
  - name: test 9
    run: echo 9

  - name: test 1
    run: echo 1

  - name: test 2
    run: echo 2
#@ end
```

Which when put into a [YAML linter](https://codebeautify.org/yaml-validator) will throw an error:

```
Error : Unable to parse.
Line : 1 uses: actions/setup-go@v2
```

If I add `---` to define several documents, it's then valid YAML, and it renders correctly. So this works:

```yaml
#@ def setup_go():
  uses: actions/setup-go@v2
  with:
    go-version: "^1.14.4"
#@ end

---

#@ def test_a():
  - name: test 9
    run: echo 9

  - name: test 1
    run: echo 1

  - name: test 2
    run: echo 2
#@ end
```

Let me know if you would like me to create a PR to include such an example in `.gflows/workflows/gflows/gflows.yml`.
