### ISSUE TITLE
reorganize config structure for workflows and templates

### ISSUE THREAD

**Issue by jbrunton** [jbrunton/gflows#89]
Move "defaults" and "workflows" under top level "workflows" option, and add "templates" option with similar overrides.

```yaml
# The .github directory. Set this if you put `gflows` in a different directory than the default.
# Default: .github
githubDir: .github

workflows:
  # Default options for generating workflows
  defaults:
    # The checks to conduct when running `gflows check`
    checks:
      schema:
        # Whether or not to validate with a JSON schema.
        # Default: true
        enabled: true
      
        # The schema to use.
        # Default: https://json.schemastore.org/github-workflow
        uri: https://example.com/my-schema

      content:
        # Whether or not to validate that the workflow in .github is up to date
        # Default: true
        enabled: true

  # Overrides for specific workflows
  overrides:
    # For example, this overrides the schema options for my-workflow
    my-workflow:
      checks:
        schema:
          enabled: false

templates:
  defaults:
    engine: jsonnet
    # Jsonnet options
    jsonnet:
      # Additional paths to search for libraries. Useful if you use jsonnet-bundler.
      # Default: <empty list>
      jpath:
      - vendor
      - my-library
  overrides:
    my-workflow:
      jsonnet:
        jpath:
        - my-lib
    other-workflow:
      engine: ytt
```
